"""
Twilio provisioning package.

White-label sub-account provisioning, phone number management,
Trust Hub operations (CNAM, Voice Integrity, A2P, SHAKEN/STIR).
"""

from .client import (
    get_master_client,
    get_sub_account_client,
    get_sub_account_client_native,
    TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN,
    TWILIO_PHONE_NUMBER,
    TWILIO_API_KEY_SID,
    TWILIO_API_KEY_SECRET,
)

from .sub_accounts import (
    create_sub_account,
    suspend_sub_account,
    reactivate_sub_account,
    create_twiml_app,
    update_twiml_app,
    create_api_key,
    provision_subscriber,
)

from .phone_numbers import (
    search_available_numbers,
    buy_phone_number,
    list_phone_numbers,
    release_phone_number,
    update_phone_number_webhooks,
)

from .voice import (
    generate_voice_token,
    create_outbound_call,
    hangup_call,
    transfer_call,
    start_recording,
    get_recording_url,
    add_conference_participant,
    remove_conference_participant,
    redirect_call_to_twiml,
    enable_voice_insights_advanced,
    get_voice_insights_settings,
    fetch_call_insights_summary,
    fetch_call_insights_events,
)

from .spam_protection import (
    get_spam_protection_status,
    get_cnam_monitor,
    update_cnam_for_number,
    cnam_lookup,
)

from .trust_hub import (
    is_master_account,
    check_secondary_profile_status,
    SECONDARY_CUSTOMER_PROFILE_POLICY_SID,
    CNAM_TRUST_PRODUCT_POLICY_SID,
    VOICE_INTEGRITY_POLICY_SID,
    VOICE_INTEGRITY_CARRIERS,
    register_business_profile,
    validate_cnam_display_name,
    create_cnam_trust_product,
    update_cnam_display_name,
    assign_numbers_to_cnam,
    submit_cnam_for_review,
    discover_cnam_trust_product,
    get_cnam_trust_product_status,
    create_a2p_brand,
    get_a2p_brand_status,
    create_messaging_service,
    add_phone_to_messaging_service,
    create_a2p_campaign,
    get_a2p_campaign_status,
    list_messaging_services,
    list_messaging_service_phone_numbers,
    discover_a2p_brands,
    discover_a2p_campaigns,
    discover_trust_hub_profiles,
    discover_full_a2p_status,
    create_voice_integrity_trust_product,
    assign_numbers_to_voice_integrity,
    submit_voice_integrity_for_review,
    get_voice_integrity_status,
    update_voice_integrity_end_user,
    resubmit_voice_integrity,
    remove_number_from_voice_integrity,
    discover_voice_integrity_products,
    create_shaken_stir_trust_product,
    assign_numbers_to_shaken_stir,
    submit_shaken_stir_for_review,
    get_shaken_stir_status,
    resubmit_shaken_stir,
    remove_number_from_shaken_stir,
    discover_shaken_stir_products,
)

__all__ = [
    # Client factories
    "get_master_client",
    "get_sub_account_client",
    "get_sub_account_client_native",
    # Credentials
    "TWILIO_ACCOUNT_SID",
    "TWILIO_AUTH_TOKEN",
    "TWILIO_PHONE_NUMBER",
    "TWILIO_API_KEY_SID",
    "TWILIO_API_KEY_SECRET",
    # Sub-accounts
    "create_sub_account",
    "suspend_sub_account",
    "reactivate_sub_account",
    "create_twiml_app",
    "update_twiml_app",
    "create_api_key",
    "provision_subscriber",
    # Phone numbers
    "search_available_numbers",
    "buy_phone_number",
    "list_phone_numbers",
    "release_phone_number",
    "update_phone_number_webhooks",
    # Voice
    "generate_voice_token",
    "create_outbound_call",
    "hangup_call",
    "transfer_call",
    "start_recording",
    "get_recording_url",
    "add_conference_participant",
    "remove_conference_participant",
    "redirect_call_to_twiml",
    "enable_voice_insights_advanced",
    "get_voice_insights_settings",
    "fetch_call_insights_summary",
    "fetch_call_insights_events",
    # Spam protection
    "get_spam_protection_status",
    "get_cnam_monitor",
    "update_cnam_for_number",
    "cnam_lookup",
    # Trust Hub
    "is_master_account",
    "SECONDARY_CUSTOMER_PROFILE_POLICY_SID",
    "CNAM_TRUST_PRODUCT_POLICY_SID",
    "VOICE_INTEGRITY_POLICY_SID",
    "VOICE_INTEGRITY_CARRIERS",
    "register_business_profile",
    "validate_cnam_display_name",
    "create_cnam_trust_product",
    "update_cnam_display_name",
    "assign_numbers_to_cnam",
    "submit_cnam_for_review",
    "discover_cnam_trust_product",
    "get_cnam_trust_product_status",
    "create_a2p_brand",
    "get_a2p_brand_status",
    "create_messaging_service",
    "add_phone_to_messaging_service",
    "create_a2p_campaign",
    "get_a2p_campaign_status",
    "list_messaging_services",
    "list_messaging_service_phone_numbers",
    "discover_a2p_brands",
    "discover_a2p_campaigns",
    "discover_trust_hub_profiles",
    "discover_full_a2p_status",
    "create_voice_integrity_trust_product",
    "assign_numbers_to_voice_integrity",
    "submit_voice_integrity_for_review",
    "get_voice_integrity_status",
    "update_voice_integrity_end_user",
    "resubmit_voice_integrity",
    "remove_number_from_voice_integrity",
    "discover_voice_integrity_products",
    "create_shaken_stir_trust_product",
    "assign_numbers_to_shaken_stir",
    "submit_shaken_stir_for_review",
    "get_shaken_stir_status",
    "resubmit_shaken_stir",
    "remove_number_from_shaken_stir",
    "discover_shaken_stir_products",
]
